const nounPhrases = [
    "swamps of nothingness",
    "illusions",
    "causal connections",
    "casual relationships",
    "shimmering veil",
    "mirage of meaning",
    "fractured reflection",
    "hall of echoes",
    "illusion of choice",
    "lens of hope",
    "compass of wonder",
    "tapestry of dreams",
    "trail of sparks",
    "loop",
    "braid",
    "DJ booth of Eternal Return",
    "glittering specter in bell-bottoms",
    "fog machines of regret",
    "haunted eight ball",
    "self-portrait in a discoball",
    "ectoplasm punch bowl",
    "tiles",
    "journey",
    "silence that speaks",
    "whisper behind the curtain",
    "shiver in the fabric of fate",
    "veil of meaning",
    "shadow of a hidden name",
    "echo in the whirlwind",
    "stillness before a voice",
    "patterns dusted",
    "unfolded silence",
    "echoes",
    "tremor of a plan",
    "glimpse behind a veil",
    "thread through the ruins",
    "thread through the tapestry",
    "thread through the labyrinth",
    "thread through the maze",
    "thread through the shadows",
    "thread through the mirror",
    "thread through the storm",
    "thread through the chaos", 
    "through the shadows thread",
    "tapestry through the mirror thread",
    "storm thread",
    "labyrinth behind a thread"
]

const verbPhrases = [
    "peer into silence",
    "clock the truth",
    "trembles before a storm",
    "speak without words",
    "cry into a whirlwind",
    "wait beneath a tablecloth",
    "unfold a hidden sheet",
    "reckon with a bobcat",
    "trace a turkey hand",
    "boogie through the veil",
    "remix with your unfished business",
    "moonwalk past your afterlife",
    "spin like a cursed",
    "ghosted through the living",
    "whisper the winning lottery numbers",
    "unravel a codex in a mirror",
    "rise",
    "witness starring harrison ford",
    "embrace the plotpoints",
    "walk",
    "veil",
    "waits",
    "hides",
    "trembles",
    "reveals",
    "revels",
    "burns",
    "barnstorms",
    "listens",
    "mourns",
    "speaks",
    "rises",
    "seals",
    "tests",
    "shatters",
    "watches",
    "answers",
    "ghosts yourself",
    "screams in lowercase",
    "vibrates",
    "glitches",
    "pouts",
    "combusts",
    "loops",
    "wobbles",
    "evaporates",
    "shimmies",
    "unplugs",
    "reboots",
    "recycles",
    "reanimates",
    "reincarnates",
    "dissolves",
    "wears sadness like",
    "wears a mask of",
    "misplaces a metaphor in",
    "dances with a copy of yourself",
    "hums a tune nobody can place",
    "forgets a mirror",
    "remixs the past",
    "punchs a clock",
    "DJs your exorcism"
]

const adjectivePhrases = [
    "boorish simplicity",
    "strict and subtle",
    "precise",
    "hidden",
    "unspoken",
    "veiled",
    "quiet",
    "sacred",
    "corrupted by soft neon",
    "buffering in the soul",
    "dressed in quantum static",
    "fluorescent and semi-",
    "fluorscent and semi-lost",
    "whiskering at 56kps",
    "tangled in cassette loops",
    "encrypted for no",
    "blinkering like almost obsolete",
    "cracked and sparkling",
    "cracked and shimmering",
    "cracked and glowing",
    "growing and caked",
    "janky but emotional",
    "outdated fashion",
    "born in a blue screen",
    "rebooted at the encore",
    "twitching under soft",
    "spun out of datastream dreams",
    "unstable but holo-cute",
    "ancient",
    "uncertain",
    "enduring",
    "cracked",
    "divine",
    "solemn",
    "invisible",
    "wandering",
    "dust-covered",
    "fire-tested",
    "imflammable",
    "wholly unbroken",
    "encased",
    "storm-borne",
    "shimmering with residue",
    "funky metaphysical",
    "semi-precious",
    "semi-automatic",
    "semi-conscious",
    "semi-abstract",
    "semi-opaque",
    "semi-structured",
    "semi-formed",
    "semi-illuminated",
    "semi-ethereal",
    "semi-legendary",
    "semi-volatile",
    "semi-permanent",
    "semi-opaque",
    "trapped in infinite",
    "lit by neon",
    "sky-wide",
    "sky-high",
    "soft with grief",
    "glowing from within",
    "carved in",
    "caved in",
    "deep and distant",
    "heavy with dialtones",
    "born in a voicemail box",
    "drapped in discolight"  
]
